
export const ADD_EBOOK_REQUEST = 'ADD_EBOOK_REQUEST'
export const ADD_EBOOK_SUCCESS = 'ADD_EBOOK_SUCCESS'
export const ADD_EBOOK_FAILED = 'ADD_EBOOK_FAILED'

export const VIEW_EBOOK_REQUEST = 'VIEW_EBOOK_REQUEST'
export const VIEW_EBOOK_SUCCESS = 'VIEW_EBOOK_SUCCESS'
export const VIEW_EBOOK_FAILED = 'VIEW_EBOOK_FAILED'
