export const ADD_BLOGWRITER_REQUEST = "ADD_BLOGWRITER_REQUEST";
export const ADD_BLOGWRITER_SUCCESS = "ADD_BLOGWRITER_SUCCESS";
export const ADD_BLOGWRITER_FAILED = "ADD_BLOGWRITER_FAILED";

export const GET_BLOGWRITER_REQUEST = "GET_BLOGWRITER_REQUEST";
export const GET_BLOGWRITER_SUCCESS = "GET_BLOGWRITER_SUCCESS";
export const GET_BLOGWRITER_FAILED = "GET_BLOGWRITER_FAILED";

export const GETONE_BLOGWRITER_REQUEST = "GETONE_BLOGWRITER_REQUEST";
export const GETONE_BLOGWRITER_SUCCESS = "GETONE_BLOGWRITER_SUCCESS";
export const GETONE_BLOGWRITER_FAILED = "GETONE_BLOGWRITER_FAILED";

export const UPDATE_BLOGWRITER_REQUEST = "UPDATE_BLOGWRITER_REQUEST";
export const UPDATE_BLOGWRITER_SUCCESS = "UPDATE_BLOGWRITER_SUCCESS";
export const UPDATE_BLOGWRITER_FAILED = "UPDATE_BLOGWRITER_FAILED";

export const DELETE_BLOGWRITER_REQUEST = "DELETE_BLOGWRITER_REQUEST";
export const DELETE_BLOGWRITER_SUCCESS = "DELETE_BLOGWRITER_SUCCESS";
export const DELETE_BLOGWRITER_FAILED = "DELETE_BLOGWRITER_FAILED";
