export const ADD_BLOGSECTION_REQUEST = "ADD_BLOGSECTION_REQUEST";
export const ADD_BLOGSECTION_SUCCESS = "ADD_BLOGSECTION_SUCCESS";
export const ADD_BLOGSECTION_FAILED = "ADD_BLOGSECTION_FAILED";

export const GET_BLOGSECTION_REQUEST = "GET_BLOGSECTION_REQUEST";
export const GET_BLOGSECTION_SUCCESS = "GET_BLOGSECTION_SUCCESS";
export const GET_BLOGSECTION_FAILED = "GET_BLOGSECTION_FAILED";

export const GETONE_BLOGSECTION_REQUEST = "GETONE_BLOGSECTION_REQUEST";
export const GETONE_BLOGSECTION_SUCCESS = "GETONE_BLOGSECTION_SUCCESS";
export const GETONE_BLOGSECTION_FAILED = "GETONE_BLOGSECTION_FAILED";

export const UPDATE_BLOGSECTION_REQUEST = "UPDATE_BLOGSECTION_REQUEST";
export const UPDATE_BLOGSECTION_SUCCESS = "UPDATE_BLOGSECTION_SUCCESS";
export const UPDATE_BLOGSECTION_FAILED = "UPDATE_BLOGSECTION_FAILED";

export const DELETE_BLOGSECTION_REQUEST = "DELETE_BLOGSECTION_REQUEST";
export const DELETE_BLOGSECTION_SUCCESS = "DELETE_BLOGSECTION_SUCCESS";
export const DELETE_BLOGSECTION_FAILED = "DELETE_BLOGSECTION_FAILED";
