export const ADD_CONCLUSION_REQUEST = "ADD_CONCLUSION_REQUEST";
export const ADD_CONCLUSION_SUCCESS = "ADD_CONCLUSION_SUCCESS";
export const ADD_CONCLUSION_FAILED = "ADD_CONCLUSION_FAILED";

export const GET_CONCLUSION_REQUEST = "GET_CONCLUSION_REQUEST";
export const GET_CONCLUSION_SUCCESS = "GET_CONCLUSION_SUCCESS";
export const GET_CONCLUSION_FAILED = "GET_CONCLUSION_FAILED";

export const GETONE_CONCLUSION_REQUEST = "GETONE_CONCLUSION_REQUEST";
export const GETONE_CONCLUSION_SUCCESS = "GETONE_CONCLUSION_SUCCESS";
export const GETONE_CONCLUSION_FAILED = "GETONE_CONCLUSION_FAILED";

export const DELETE_CONCLUSION_REQUEST = "DELETE_CONCLUSION_REQUEST";
export const DELETE_CONCLUSION_SUCCESS = "DELETE_CONCLUSION_SUCCESS";
export const DELETE_CONCLUSION_FAILED = "DELETE_CONCLUSION_FAILED";
