export const ADD_LANDINGPAGE_REQUEST = "ADD_LANDINGPAGE_REQUEST";
export const ADD_LANDINGPAGE_SUCCESS = "ADD_LANDINGPAGE_SUCCESS";
export const ADD_LANDINGPAGE_FAILED = "ADD_LANDINGPAGE_FAILED";

export const GET_LANDINGPAGE_REQUEST = "GET_LANDINGPAGE_REQUEST";
export const GET_LANDINGPAGE_SUCCESS = "GET_LANDINGPAGE_SUCCESS";
export const GET_LANDINGPAGE_FAILED = "GET_LANDINGPAGE_FAILED";

export const GETONE_LANDINGPAGE_REQUEST = "GETONE_LANDINGPAGE_REQUEST";
export const GETONE_LANDINGPAGE_SUCCESS = "GETONE_LANDINGPAGE_SUCCESS";
export const GETONE_LANDINGPAGE_FAILED = "GETONE_LANDINGPAGE_FAILED";

export const DELETE_LANDINGPAGE_REQUEST = "DELETE_LANDINGPAGE_REQUEST";
export const DELETE_LANDINGPAGE_SUCCESS = "DELETE_LANDINGPAGE_SUCCESS";
export const DELETE_LANDINGPAGE_FAILED = "DELETE_LANDINGPAGE_FAILED";
