export const ADD_LINKDLN_REQUEST = "ADD_LINKDLN_REQUEST";
export const ADD_LINKDLN_SUCCESS = "ADD_LINKDLN_SUCCESS";
export const ADD_LINKDLN_FAILED = "ADD_LINKDLN_FAILED";

export const GET_LINKDLN_REQUEST = "GET_LINKDLN_REQUEST";
export const GET_LINKDLN_SUCCESS = "GET_LINKDLN_SUCCESS";
export const GET_LINKDLN_FAILED = "GET_LINKDLN_FAILED";

export const GETONE_LINKDLN_REQUEST = "GETONE_LINKDLN_REQUEST";
export const GETONE_LINKDLN_SUCCESS = "GETONE_LINKDLN_SUCCESS";
export const GETONE_LINKDLN_FAILED = "GETONE_LINKDLN_FAILED";

export const DELETE_LINKDLN_REQUEST = "DELETE_LINKDLN_REQUEST";
export const DELETE_LINKDLN_SUCCESS = "DELETE_LINKDLN_SUCCESS";
export const DELETE_LINKDLN_FAILED = "DELETE_LINKDLN_FAILED";
