export const USERS_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USERS_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USERS_LOGIN_FAILED = "USER_LOGIN_FAILED";
export const USERS_LOGOUT = "USER_LOGOUT";


export const USERS_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USERS_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USERS_REGISTER_FAILED = "USER_REGISTER_FAILED";


export const USERS_PROFILE_REQUEST = "USER_PROFILE_REQUEST";
export const USERS_PROFILE_SUCCESS = "USER_PROFILE_SUCCESS";
export const USERS_PROFILE_FAILED = "USER_PROFILE_FAILED";

export const GOOGLE_USER_REQUEST = "GOOGLE_USER_REQUEST";
export const GOOGLE_USER_SUCCESS = "GOOGLE_USER_SUCCESS";
export const GOOGLE_USER_FAILED = "GOOGLE_USER_FAILED";


