export const ADD_BLOGARTICLEWRITER_REQUEST = "ADD_BLOGARTICLEWRITER_REQUEST"
export const ADD_BLOGARTICLEWRITER_SUCCESS = "ADD_BLOGARTICLEWRITER_SUCCESS"
export const ADD_BLOGARTICLEWRITER_FAILED = "ADD_BLOGARTICLEWRITER_FAILED"
