export const ADD_ARTICLEREWRITER_REQUEST = 'ADD_ARTICLEREWRITER_REQUEST'
export const ADD_ARTICLEREWRITER_SUCCESS = 'ADD_ARTICLEREWRITER_SUCCESS'
export const ADD_ARTICLEREWRITER_FAILED = 'ADD_ARTICLEREWRITER_FAILED'