export const ADD_AUDIO_REQUEST = "ADD_AUDIO_REQUEST";
export const ADD_AUDIO_SUCCESS = "ADD_AUDIO_SUCCESS";
export const ADD_AUDIO_FAILED = "ADD_AUDIO_FAILED";

export const GET_AUDIO_REQUEST = "GET_AUDIO_REQUEST";
export const GET_AUDIO_SUCCESS = "GET_AUDIO_SUCCESS";
export const GET_AUDIO_FAILED = "GET_AUDIO_FAILED";

export const GETONE_AUDIO_REQUEST = "GETONE_AUDIO_REQUEST";
export const GETONE_AUDIO_SUCCESS = "GETONE_AUDIO_SUCCESS";
export const GETONE_AUDIO_FAILED = "GETONE_AUDIO_FAILED";

export const DELETE_AUDIO_REQUEST = "DELETE_AUDIO_REQUEST";
export const DELETE_AUDIO_SUCCESS = "DELETE_AUDIO_SUCCESS";
export const DELETE_AUDIO_FAILED = "DELETE_AUDIO_FAILED";
