export const ADD_EBOOK_REQUEST = "ADD_EBOOK_REQUEST";
export const ADD_EBOOK_SUCCESS = "ADD_EBOOK_SUCCESS";
export const ADD_EBOOK_FAILED = "ADD_EBOOK_FAILED";

export const GET_EBOOK_REQUEST = "GET_EBOOK_REQUEST";
export const GET_EBOOK_SUCCESS = "GET_EBOOK_SUCCESS";
export const GET_EBOOK_FAILED = "GET_EBOOK_FAILED";

export const GETONE_EBOOK_REQUEST = "GETONE_EBOOK_REQUEST";
export const GETONE_EBOOK_SUCCESS = "GETONE_EBOOK_SUCCESS";
export const GETONE_EBOOK_FAILED = "GETONE_EBOOK_FAILED";

export const DELETE_EBOOK_REQUEST = "DELETE_EBOOK_REQUEST";
export const DELETE_EBOOK_SUCCESS = "DELETE_EBOOK_SUCCESS";
export const DELETE_EBOOK_FAILED = "DELETE_EBOOK_FAILED";
