export const ADD_EMAILGEN_REQUEST = "ADD_EMAILGEN_REQUEST";
export const ADD_EMAILGEN_SUCCESS = "ADD_EMAILGEN_SUCCESS";
export const ADD_EMAILGEN_FAILED = "ADD_EMAILGEN_FAILED";

export const GET_EMAILGEN_REQUEST = "GET_EMAILGEN_REQUEST";
export const GET_EMAILGEN_SUCCESS = "GET_EMAILGEN_SUCCESS";
export const GET_EMAILGEN_FAILED = "GET_EMAILGEN_FAILED";

export const GETONE_EMAILGEN_REQUEST = "GETONE_EMAILGEN_REQUEST";
export const GETONE_EMAILGEN_SUCCESS = "GETONE_EMAILGEN_SUCCESS";
export const GETONE_EMAILGEN_FAILED = "GETONE_EMAILGEN_FAILED";

export const UPDATE_EMAILGEN_REQUEST = "UPDATE_EMAILGEN_REQUEST";
export const UPDATE_EMAILGEN_SUCCESS = "UPDATE_EMAILGEN_SUCCESS";
export const UPDATE_EMAILGEN_FAILED = "UPDATE_EMAILGEN_FAILED";

export const DELETE_EMAILGEN_REQUEST = "DELETE_EMAILGEN_REQUEST";
export const DELETE_EMAILGEN_SUCCESS = "DELETE_EMAILGEN_SUCCESS";
export const DELETE_EMAILGEN_FAILED = "DELETE_CONTENTREPRE_FAILED";
