export const ADD_EMAILSUBJECT_REQUEST = "ADD_EMAILSUBJECT_REQUEST";
export const ADD_EMAILSUBJECT_SUCCESS = "ADD_EMAILSUBJECT_SUCCESS";
export const ADD_EMAILSUBJECT_FAILED = "ADD_EMAILSUBJECT_FAILED";

export const GET_EMAILSUBJECT_REQUEST = "GET_EMAILSUBJECT_REQUEST";
export const GET_EMAILSUBJECT_SUCCESS = "GET_EMAILSUBJECT_SUCCESS";
export const GET_EMAILSUBJECT_FAILED = "GET_EMAILSUBJECT_FAILED";

export const GETONE_EMAILSUBJECT_REQUEST = "GETONE_EMAILSUBJECT_REQUEST";
export const GETONE_EMAILSUBJECT_SUCCESS = "GETONE_EMAILSUBJECT_SUCCESS";
export const GETONE_EMAILSUBJECT_FAILED = "GETONE_EMAILSUBJECT_FAILED";

export const UPDATE_EMAILSUBJECT_REQUEST = "UPDATE_EMAILSUBJECT_REQUEST";
export const UPDATE_EMAILSUBJECT_SUCCESS = "UPDATE_EMAILSUBJECT_SUCCESS";
export const UPDATE_EMAILSUBJECT_FAILED = "UPDATE_EMAILSUBJECT_FAILED";

export const DELETE_EMAILSUBJECT_REQUEST = "DELETE_EMAILSUBJECT_REQUEST";
export const DELETE_EMAILSUBJECT_SUCCESS = "DELETE_EMAILSUBJECT_SUCCESS";
export const DELETE_EMAILSUBJECT_FAILED = "DELETE_EMAILSUBJECT_FAILED";
