export const ADD_FACEBOOKADS_REQUEST = "ADD_FACEBOOKADS_REQUEST";
export const ADD_FACEBOOKADS_SUCCESS = "ADD_FACEBOOKADS_SUCCESS";
export const ADD_FACEBOOKADS_FAILED = "ADD_FACEBOOKADS_FAILED";

export const GET_FACEBOOKADS_REQUEST = "GET_FACEBOOKADS_REQUEST";
export const GET_FACEBOOKADS_SUCCESS = "GET_FACEBOOKADS_SUCCESS";
export const GET_FACEBOOKADS_FAILED = "GET_FACEBOOKADS_FAILED";

export const GETONE_FACEBOOKADS_REQUEST = "GETONE_FACEBOOKADS_REQUEST";
export const GETONE_FACEBOOKADS_SUCCESS = "GETONE_FACEBOOKADS_SUCCESS";
export const GETONE_FACEBOOKADS_FAILED = "GETONE_FACEBOOKADS_FAILED";

export const DELETE_FACEBOOKADS_REQUEST = "DELETE_FACEBOOKADS_REQUEST";
export const DELETE_FACEBOOKADS_SUCCESS = "DELETE_FACEBOOKADS_SUCCESS";
export const DELETE_FACEBOOKADS_FAILED = "DELETE_FACEBOOKADS_FAILED";
