export const ADD_GOOGLEADS_REQUEST = "ADD_GOOGLEADS_REQUEST";
export const ADD_GOOGLEADS_SUCCESS = "ADD_GOOGLEADS_SUCCESS";
export const ADD_GOOGLEADS_FAILED = "ADD_GOOGLEADS_FAILED";

export const GET_GOOGLEADS_REQUEST = "GET_GOOGLEADS_REQUEST";
export const GET_GOOGLEADS_SUCCESS = "GET_GOOGLEADS_SUCCESS";
export const GET_GOOGLEADS_FAILED = "GET_GOOGLEADS_FAILED";

export const GETONE_GOOGLEADS_REQUEST = "GETONE_GOOGLEADS_REQUEST";
export const GETONE_GOOGLEADS_SUCCESS = "GETONE_GOOGLEADS_SUCCESS";
export const GETONE_GOOGLEADS_FAILED = "GETONE_GOOGLEADS_FAILED";

export const DELETE_GOOGLEADS_REQUEST = "DELETE_GOOGLEADS_REQUEST";
export const DELETE_GOOGLEADS_SUCCESS = "DELETE_GOOGLEADS_SUCCESS";
export const DELETE_GOOGLEADS_FAILED = "DELETE_GOOGLEADS_FAILED";
