export const ADD_GOOGLETITLE_REQUEST = "ADD_GOOGLETITLE_REQUEST";
export const ADD_GOOGLETITLE_SUCCESS = "ADD_GOOGLETITLE_SUCCESS";
export const ADD_GOOGLETITLE_FAILED = "ADD_GOOGLETITLE_FAILED";

export const GET_GOOGLETITLE_REQUEST = "GET_GOOGLETITLE_REQUEST";
export const GET_GOOGLETITLE_SUCCESS = "GET_GOOGLETITLE_SUCCESS";
export const GET_GOOGLETITLE_FAILED = "GET_GOOGLETITLE_FAILED";

export const GETONE_GOOGLETITLE_REQUEST = "GETONE_GOOGLETITLE_REQUEST";
export const GETONE_GOOGLETITLE_SUCCESS = "GETONE_GOOGLETITLE_SUCCESS";
export const GETONE_GOOGLETITLE_FAILED = "GETONE_GOOGLETITLE_FAILED";

export const DELETE_GOOGLETITLE_REQUEST = "DELETE_GOOGLETITLE_REQUEST";
export const DELETE_GOOGLETITLE_SUCCESS = "DELETE_GOOGLETITLE_SUCCESS";
export const DELETE_GOOGLETITLE_FAILED = "DELETE_GOOGLETITLE_FAILED";
