export const ADD_IMAGE_REQUEST = "ADD_IMAGE_REQUEST";
export const ADD_IMAGE_SUCCESS = "ADD_IMAGE_SUCCESS";
export const ADD_IMAGE_FAILED = "ADD_IMAGE_FAILED";

export const GET_IMAGE_REQUEST = "GET_IMAGE_REQUEST";
export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";
export const GET_IMAGE_FAILED = "GET_IMAGE_FAILED";

export const GETONE_IMAGE_REQUEST = "GETONE_IMAGE_REQUEST";
export const GETONE_IMAGE_SUCCESS = "GETONE_IMAGE_SUCCESS";
export const GETONE_IMAGE_FAILED = "GETONE_IMAGE_FAILED";

export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_FAILED = "DELETE_IMAGE_FAILED";
