export const ADD_INSTAGRAMCAP_REQUEST = "ADD_INSTAGRAMCAP_REQUEST";
export const ADD_INSTAGRAMCAP_SUCCESS = "ADD_INSTAGRAMCAP_SUCCESS";
export const ADD_INSTAGRAMCAP_FAILED = "ADD_INSTAGRAMCAP_FAILED";

export const GET_INSTAGRAMCAP_REQUEST = "GET_INSTAGRAMCAP_REQUEST";
export const GET_INSTAGRAMCAP_SUCCESS = "GET_INSTAGRAMCAP_SUCCESS";
export const GET_INSTAGRAMCAP_FAILED = "GET_INSTAGRAMCAP_FAILED";

export const GETONE_INSTAGRAMCAP_REQUEST = "GETONE_INSTAGRAMCAP_REQUEST";
export const GETONE_INSTAGRAMCAP_SUCCESS = "GETONE_INSTAGRAMCAP_SUCCESS";
export const GETONE_INSTAGRAMCAP_FAILED = "GETONE_INSTAGRAMCAP_FAILED";

export const DELETE_INSTAGRAMCAP_REQUEST = "DELETE_INSTAGRAMCAP_REQUEST";
export const DELETE_INSTAGRAMCAP_SUCCESS = "DELETE_INSTAGRAMCAP_SUCCESS";
export const DELETE_INSTAGRAMCAP_FAILED = "DELETE_INSTAGRAMCAP_FAILED";
