export const ADD_LANGUAGE_REQUEST = "ADD_LANGUAGE_REQUEST";
export const ADD_LANGUAGE_SUCCESS = "ADD_LANGUAGE_SUCCESS";
export const ADD_LANGUAGE_FAILED = "ADD_LANGUAGE_FAILED";

export const GET_LANGUAGE_REQUEST = "GET_LANGUAGE_REQUEST";
export const GET_LANGUAGE_SUCCESS = "GET_LANGUAGE_SUCCESS";
export const GET_LANGUAGE_FAILED = "GET_LANGUAGE_FAILED";

export const GETONE_LANGUAGE_REQUEST = "GETONE_LANGUAGE_REQUEST";
export const GETONE_LANGUAGE_SUCCESS = "GETONE_LANGUAGE_SUCCESS";
export const GETONE_LANGUAGE_FAILED = "GETONE_LANGUAGE_FAILED";

export const DELETE_LANGUAGE_REQUEST = "DELETE_LANGUAGE_REQUEST";
export const DELETE_LANGUAGE_SUCCESS = "DELETE_LANGUAGE_SUCCESS";
export const DELETE_LANGUAGE_FAILED = "DELETE_LANGUAGE_FAILED";
