export const ADD_LINKDINADS_REQUEST = "ADD_LINKDINADS_REQUEST";
export const ADD_LINKDINADS_SUCCESS = "ADD_LINKDINADS_SUCCESS";
export const ADD_LINKDINADS_FAILED = "ADD_LINKDINADS_FAILED";

export const GET_LINKDINADS_REQUEST = "GET_LINKDINADS_REQUEST";
export const GET_LINKDINADS_SUCCESS = "GET_LINKDINADS_SUCCESS";
export const GET_LINKDINADS_FAILED = "GET_LINKDINADS_FAILED";

export const GETONE_LINKDINADS_REQUEST = "GETONE_LINKDINADS_REQUEST";
export const GETONE_LINKDINADS_SUCCESS = "GETONE_LINKDINADS_SUCCESS";
export const GETONE_LINKDINADS_FAILED = "GETONE_LINKDINADS_FAILED";

export const DELETE_LINKDINADS_REQUEST = "DELETE_LINKDINADS_REQUEST";
export const DELETE_LINKDINADS_SUCCESS = "DELETE_LINKDINADS_SUCCESS";
export const DELETE_LINKDINADS_FAILED = "DELETE_LINKDINADS_FAILED";
