export const ADD_PARAGRAPH_REQUEST = "ADD_PARAGRAPH_REQUEST";
export const ADD_PARAGRAPH_SUCCESS = "ADD_PARAGRAPH_SUCCESS";
export const ADD_PARAGRAPH_FAILED = "ADD_PARAGRAPH_FAILED";

export const GET_PARAGRAPH_REQUEST = "GET_PARAGRAPH_REQUEST";
export const GET_PARAGRAPH_SUCCESS = "GET_PARAGRAPH_SUCCESS";
export const GET_PARAGRAPH_FAILED = "GET_PARAGRAPH_FAILED";

export const GETONE_PARAGRAPH_REQUEST = "GETONE_PARAGRAPH_REQUEST";
export const GETONE_PARAGRAPH_SUCCESS = "GETONE_PARAGRAPH_SUCCESS";
export const GETONE_PARAGRAPH_FAILED = "GETONE_PARAGRAPH_FAILED";

export const DELETE_PARAGRAPH_REQUEST = "DELETE_PARAGRAPH_REQUEST";
export const DELETE_PARAGRAPH_SUCCESS = "DELETE_PARAGRAPH_SUCCESS";
export const DELETE_PARAGRAPH_FAILED = "DELETE_PARAGRAPH_FAILED";
