export const ADD_PRODUCTNAME_REQUEST = "ADD_PRODUCTNAME_REQUEST";
export const ADD_PRODUCTNAME_SUCCESS = "ADD_PRODUCTNAME_SUCCESS";
export const ADD_PRODUCTNAME_FAILED = "ADD_PRODUCTNAME_FAILED";

export const GET_PRODUCTNAME_REQUEST = "GET_PRODUCTNAME_REQUEST";
export const GET_PRODUCTNAME_SUCCESS = "GET_PRODUCTNAME_SUCCESS";
export const GET_PRODUCTNAME_FAILED = "GET_PRODUCTNAME_FAILED";

export const GETONE_PRODUCTNAME_REQUEST = "GETONE_PRODUCTNAME_REQUEST";
export const GETONE_PRODUCTNAME_SUCCESS = "GETONE_PRODUCTNAME_SUCCESS";
export const GETONE_PRODUCTNAME_FAILED = "GETONE_PRODUCTNAME_FAILED";

export const DELETE_PRODUCTNAME_REQUEST = "DELETE_PRODUCTNAME_REQUEST";
export const DELETE_PRODUCTNAME_SUCCESS = "DELETE_PRODUCTNAME_SUCCESS";
export const DELETE_PRODUCTNAME_FAILED = "DELETE_PRODUCTNAME_FAILED";
