export const ADD_PRODUCTDESC_REQUEST = "ADD_PRODUCTDESC_REQUEST";
export const ADD_PRODUCTDESC_SUCCESS = "ADD_PRODUCTDESC_SUCCESS";
export const ADD_PRODUCTDESC_FAILED = "ADD_PRODUCTDESC_FAILED";

export const GET_PRODUCTDESC_REQUEST = "GET_PRODUCTDESC_REQUEST";
export const GET_PRODUCTDESC_SUCCESS = "GET_PRODUCTDESC_SUCCESS";
export const GET_PRODUCTDESC_FAILED = "GET_PRODUCTDESC_FAILED";

export const GETONE_PRODUCTDESC_REQUEST = "GETONE_PRODUCTDESC_REQUEST";
export const GETONE_PRODUCTDESC_SUCCESS = "GETONE_PRODUCTDESC_SUCCESS";
export const GETONE_PRODUCTDESC_FAILED = "GETONE_PRODUCTDESC_FAILED";

export const DELETE_PRODUCTDESC_REQUEST = "DELETE_PRODUCTDESC_REQUEST";
export const DELETE_PRODUCTDESC_SUCCESS = "DELETE_PRODUCTDESC_SUCCESS";
export const DELETE_PRODUCTDESC_FAILED = "DELETE_PRODUCTDESC_FAILED";
