export const ADD_TWEETGEN_REQUEST = "ADD_TWEETGEN_REQUEST";
export const ADD_TWEETGEN_SUCCESS = "ADD_TWEETGEN_SUCCESS";
export const ADD_TWEETGEN_FAILED = "ADD_TWEETGEN_FAILED";

export const GET_TWEETGEN_REQUEST = "GET_TWEETGEN_REQUEST";
export const GET_TWEETGEN_SUCCESS = "GET_TWEETGEN_SUCCESS";
export const GET_TWEETGEN_FAILED = "GET_TWEETGEN_FAILED";

export const GETONE_TWEETGEN_REQUEST = "GETONE_TWEETGEN_REQUEST";
export const GETONE_TWEETGEN_SUCCESS = "GETONE_TWEETGEN_SUCCESS";
export const GETONE_TWEETGEN_FAILED = "GETONE_TWEETGEN_FAILED";

export const DELETE_TWEETGEN_REQUEST = "DELETE_TWEETGEN_REQUEST";
export const DELETE_TWEETGEN_SUCCESS = "DELETE_TWEETGEN_SUCCESS";
export const DELETE_TWEETGEN_FAILED = "DELETE_TWEETGEN_FAILED";
