export const ADD_UPLOAD_REQUEST = "ADD_UPLOAD_REQUEST";
export const ADD_UPLOAD_SUCCESS = "ADD_UPLOAD_SUCCESS";
export const ADD_UPLOAD_FAILED = "ADD_UPLOAD_FAILED";

export const GET_UPLOAD_REQUEST = "GET_UPLOAD_REQUEST";
export const GET_UPLOAD_SUCCESS = "GET_UPLOAD_SUCCESS";
export const GET_UPLOAD_FAILED = "GET_UPLOAD_FAILED";

export const GETONE_UPLOAD_REQUEST = "GETONE_UPLOAD_REQUEST";
export const GETONE_UPLOAD_SUCCESS = "GETONE_UPLOAD_SUCCESS";
export const GETONE_UPLOAD_FAILED = "GETONE_UPLOAD_FAILED";

export const DELETE_UPLOAD_REQUEST = "DELETE_UPLOAD_REQUEST";
export const DELETE_UPLOAD_SUCCESS = "DELETE_UPLOAD_SUCCESS";
export const DELETE_UPLOAD_FAILED = "DELETE_UPLOAD_FAILED";