export const ADD_YOUTUBEDESC_REQUEST = "ADD_YOUTUBEDESC_REQUEST";
export const ADD_YOUTUBEDESC_SUCCESS = "ADD_YOUTUBEDESC_SUCCESS";
export const ADD_YOUTUBEDESC_FAILED = "ADD_YOUTUBEDESC_FAILED";

export const GET_YOUTUBEDESC_REQUEST = "GET_YOUTUBEDESC_REQUEST";
export const GET_YOUTUBEDESC_SUCCESS = "GET_YOUTUBEDESC_SUCCESS";
export const GET_YOUTUBEDESC_FAILED = "GET_YOUTUBEDESC_FAILED";

export const GETONE_YOUTUBEDESC_REQUEST = "GETONE_YOUTUBEDESC_REQUEST";
export const GETONE_YOUTUBEDESC_SUCCESS = "GETONE_YOUTUBEDESC_SUCCESS";
export const GETONE_YOUTUBEDESC_FAILED = "GETONE_YOUTUBEDESC_FAILED";

export const DELETE_YOUTUBEDESC_REQUEST = "DELETE_YOUTUBEDESC_REQUEST";
export const DELETE_YOUTUBEDESC_SUCCESS = "DELETE_YOUTUBEDESC_SUCCESS";
export const DELETE_YOUTUBEDESC_FAILED = "DELETE_YOUTUBEDESC_FAILED";
