export const ADD_YOUTUBE_REQUEST = "ADD_YOUTUBE_REQUEST";
export const ADD_YOUTUBE_SUCCESS = "ADD_YOUTUBE_SUCCESS";
export const ADD_YOUTUBE_FAILED = "ADD_YOUTUBE_FAILED";

export const GET_YOUTUBE_REQUEST = "GET_YOUTUBE_REQUEST";
export const GET_YOUTUBE_SUCCESS = "GET_YOUTUBE_SUCCESS";
export const GET_YOUTUBE_FAILED = "GET_YOUTUBE_FAILED";

export const GETONE_YOUTUBE_REQUEST = "GETONE_YOUTUBE_REQUEST";
export const GETONE_YOUTUBE_SUCCESS = "GETONE_YOUTUBE_SUCCESS";
export const GETONE_YOUTUBE_FAILED = "GETONE_YOUTUBE_FAILED";

export const DELETE_YOUTUBE_REQUEST = "DELETE_YOUTUBE_REQUEST";
export const DELETE_YOUTUBE_SUCCESS = "DELETE_YOUTUBE_SUCCESS";
export const DELETE_YOUTUBE_FAILED = "DELETE_YOUTUBE_FAILED";
