export const ADD_ARTICLEWRITTER_REQUEST = "ADD_ARTICLEWRITTER_REQUEST";
export const ADD_ARTICLEWRITTER_SUCCESS = "ADD_ARTICLEWRITTER_SUCCESS";
export const ADD_ARTICLEWRITTER_FAILED = "ADD_ARTICLEWRITTER_FAILED";

export const GET_ARTICLEWRITTER_REQUEST = "GET_ARTICLEWRITTER_REQUEST";
export const GET_ARTICLEWRITTER_SUCCESS = "GET_ARTICLEWRITTER_SUCCESS";
export const GET_ARTICLEWRITTER_FAILED = "GET_ARTICLEWRITTER_FAILED";

export const GETONE_ARTICLEWRITTER_REQUEST = "GETONE_ARTICLEWRITTER_REQUEST";
export const GETONE_ARTICLEWRITTER_SUCCESS = "GETONE_ARTICLEWRITTER_SUCCESS";
export const GETONE_ARTICLEWRITTER_FAILED = "GETONE_ARTICLEWRITTER_FAILED";


export const UPDATE_ARTICLEWRITTER_REQUEST = "UPDATE_ARTICLEWRITTER_REQUEST";
export const UPDATE_ARTICLEWRITTER_SUCCESS = "UPDATE_ARTICLEWRITTER_SUCCESS";
export const UPDATE_ARTICLEWRITTER_FAILED = "UPDATE_ARTICLEWRITTER_FAILED";

export const DELETE_ARTICLEWRITTER_REQUEST = "DELETE_ARTICLEWRITTER_REQUEST";
export const DELETE_ARTICLEWRITTER_SUCCESS = "DELETE_ARTICLEWRITTER_SUCCESS";
export const DELETE_ARTICLEWRITTER_FAILED = "DELETE_ARTICLEWRITTER_FAILED";
