export const ADD_BLOGINTRO_REQUEST = "ADD_BLOGINTRO_REQUEST";
export const ADD_BLOGINTRO_SUCCESS = "ADD_BLOGINTRO_SUCCESS";
export const ADD_BLOGINTRO_FAILED = "ADD_BLOGINTRO_FAILED";

export const GET_BLOGINTRO_REQUEST = "GET_BLOGINTRO_REQUEST";
export const GET_BLOGINTRO_SUCCESS = "GET_BLOGINTRO_SUCCESS";
export const GET_BLOGINTRO_FAILED = "GET_BLOGINTRO_FAILED";

export const GETONE_BLOGINTRO_REQUEST = "GETONE_BLOGINTRO_REQUEST";
export const GETONE_BLOGINTRO_SUCCESS = "GETONE_BLOGINTRO_SUCCESS";
export const GETONE_BLOGINTRO_FAILED = "GETONE_BLOGINTRO_FAILED";

export const DELETE_BLOGINTRO_REQUEST = "DELETE_BLOGINTRO_REQUEST";
export const DELETE_BLOGINTRO_SUCCESS = "DELETE_BLOGINTRO_SUCCESS";
export const DELETE_BLOGINTRO_FAILED = "DELETE_BLOGINTRO_FAILED";
