export const ADD_BLOGTOPIC_REQUEST = "ADD_BLOGTOPIC_REQUEST";
export const ADD_BLOGTOPIC_SUCCESS = "ADD_BLOGTOPIC_SUCCESS";
export const ADD_BLOGTOPIC_FAILED = "ADD_BLOGTOPIC_FAILED";

export const GET_BLOGTOPIC_REQUEST = "GET_BLOGTOPIC_REQUEST";
export const GET_BLOGTOPIC_SUCCESS = "GET_BLOGTOPIC_SUCCESS";
export const GET_BLOGTOPIC_FAILED = "GET_BLOGTOPIC_FAILED";

export const GETONE_BLOGTOPIC_REQUEST = "GETONE_BLOGTOPIC_REQUEST";
export const GETONE_BLOGTOPIC_SUCCESS = "GETONE_BLOGTOPIC_SUCCESS";
export const GETONE_BLOGTOPIC_FAILED = "GETONE_BLOGTOPIC_FAILED";

export const UPDATE_BLOGTOPIC_REQUEST = "UPDATE_BLOGTOPIC_REQUEST";
export const UPDATE_BLOGTOPIC_SUCCESS = "UPDATE_BLOGTOPIC_SUCCESS";
export const UPDATE_BLOGTOPIC_FAILED = "UPDATE_BLOGTOPIC_FAILED";

export const DELETE_BLOGTOPIC_REQUEST = "DELETE_BLOGTOPIC_REQUEST";
export const DELETE_BLOGTOPIC_SUCCESS = "DELETE_BLOGTOPIC_SUCCESS";
export const DELETE_BLOGTOPIC_FAILED = "DELETE_BLOGTOPIC_FAILED";
