export const ADD_CONTENTREPRE_REQUEST = "ADD_CONTENTREPRE_REQUEST";
export const ADD_CONTENTREPRE_SUCCESS = "ADD_CONTENTREPRE_SUCCESS";
export const ADD_CONTENTREPRE_FAILED = "ADD_CONTENTREPRE_FAILED";

export const GET_CONTENTREPRE_REQUEST = "GET_CONTENTREPRE_REQUEST";
export const GET_CONTENTREPRE_SUCCESS = "GET_CONTENTREPRE_SUCCESS";
export const GET_CONTENTREPRE_FAILED = "GET_CONTENTREPRE_FAILED";

export const GETONE_CONTENTREPRE_REQUEST = "GETONE_CONTENTREPRE_REQUEST";
export const GETONE_CONTENTREPRE_SUCCESS = "GETONE_CONTENTREPRE_SUCCESS";
export const GETONE_CONTENTREPRE_FAILED = "GETONE_CONTENTREPRE_FAILED";

export const UPDATE_CONTENTREPRE_REQUEST = "UPDATE_CONTENTREPRE_REQUEST";
export const UPDATE_CONTENTREPRE_SUCCESS = "UPDATE_CONTENTREPRE_SUCCESS";
export const UPDATE_CONTENTREPRE_FAILED = "UPDATE_CONTENTREPRE_FAILED";

export const DELETE_CONTENTREPRE_REQUEST = "DELETE_CONTENTREPRE_REQUEST";
export const DELETE_CONTENTREPRE_SUCCESS = "DELETE_CONTENTREPRE_SUCCESS";
export const DELETE_CONTENTREPRE_FAILED = "DELETE_CONTENTREPRE_FAILED";
