export const ADD_LANDINGHEADLINE_REQUEST = "ADD_LANDINGHEADLINE_REQUEST";
export const ADD_LANDINGHEADLINE_SUCCESS = "ADD_LANDINGHEADLINE_SUCCESS";
export const ADD_LANDINGHEADLINE_FAILED = "ADD_LANDINGHEADLINE_FAILED";

export const GET_LANDINGHEADLINE_REQUEST = "GET_LANDINGHEADLINE_REQUEST";
export const GET_LANDINGHEADLINE_SUCCESS = "GET_LANDINGHEADLINE_SUCCESS";
export const GET_LANDINGHEADLINE_FAILED = "GET_LANDINGHEADLINE_FAILED";

export const GETONE_LANDINGHEADLINE_REQUEST = "GETONE_LANDINGHEADLINE_REQUEST";
export const GETONE_LANDINGHEADLINE_SUCCESS = "GETONE_LANDINGHEADLINE_SUCCESS";
export const GETONE_LANDINGHEADLINE_FAILED = "GETONE_LANDINGHEADLINE_FAILED";

export const DELETE_LANDINGHEADLINE_REQUEST = "DELETE_LANDINGHEADLINE_REQUEST";
export const DELETE_LANDINGHEADLINE_SUCCESS = "DELETE_LANDINGHEADLINE_SUCCESS";
export const DELETE_LANDINGHEADLINE_FAILED = "DELETE_LANDINGHEADLINE_FAILED";
