export const ADD_ARTICLEBLOG_REQUEST = 'ADD_ARTICLEBLOG_REQUEST'
export const ADD_ARTICLEBLOG_SUCCESS = 'ADD_ARTICLEBLOG_SUCCESS'
export const ADD_ARTICLEBLOG_FAILED = 'ADD_ARTICLEBLOG_FAILED'

export const GET_ARTICLEBLOG_REQUEST = 'GET_ARTICLEBLOG_REQUEST'
export const GET_ARTICLEBLOG_SUCCESS = 'GET_ARTICLEBLOG_SUCCESS'
export const GET_ARTICLEBLOG_FAILED = 'GET_ARTICLEBLOG_FAILED'
