export const ADD_BLOGINTRO_REQUEST = "ADD_BLOGINTRO_REQUEST"
export const ADD_BLOGINTRO_SUCCESS = "ADD_BLOGINTRO_SUCCESS"
export const ADD_BLOGINTRO_FAILED = "ADD_BLOGINTRO_FAILED"


export const GET_BLOGINTRO_REQUEST = "GET_BLOGINTRO_REQUEST"
export const GET_BLOGINTRO_SUCCESS = "GET_BLOGINTRO_SUCCESS"
export const GET_BLOGINTRO_FAILED = "GET_BLOGINTRO_FAILED"


