export const ADD_CONTENTREPRESAL_REQUEST = 'ADD_CONTENTREPRESAL_REQUEST'
export const ADD_CONTENTREPRESAL_SUCCESS = 'ADD_CONTENTREPRESAL_SUCCESS'
export const ADD_CONTENTREPRESAL_FAILED = 'ADD_CONTENTREPRESAL_FAILED'