export const ADD_GOOGLEADSTITLE_REQUEST = "ADD_GOOGLEADSTITLE_REQUEST"
export const ADD_GOOGLEADSTITLE_SUCCESS = "ADD_GOOGLEADSTITLE_SUCCESS"
export const ADD_GOOGLEADSTITLE_FAILED  = "ADD_GOOGLEADSTITLE_FAILED"